version: "3"

services:
  pruebatec01:
    build: PruebaTecnica01
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://pruebaTec01:3306/pruebaTec01?createDatabaseIdNotExist=true&serverTimezone=UTC
      DB_PASSWORD: root
      DB_USER_NAME: root
    restart: always
    depends_on:
      pruebaTec01:
        condition: service_healthy

  pruebaTec01:
    image: mysql:9.5.0
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pruebaTec01
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
